/* Database export results for db blog */

/* Preserve session variables */
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS;
SET FOREIGN_KEY_CHECKS=0;

/* Export data */

/* Table structure for comment */
CREATE TABLE `comment` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `comment` varchar(1024) DEFAULT NULL,
  `post_id` int(11) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=latin1;

/* data for Table comment */
INSERT INTO `comment` VALUES (1,"The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.",1,"2018-07-29 14:53:39");
INSERT INTO `comment` VALUES (2,"The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.",1,"2018-07-29 14:53:39");
INSERT INTO `comment` VALUES (3,"The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.",1,"2018-07-29 14:53:39");
INSERT INTO `comment` VALUES (4,"nice blog\\r\\n",2,"2018-07-29 15:00:24");

/* Table structure for post */
CREATE TABLE `post` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` text,
  `content` mediumtext,
  `image` varchar(256) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `total_views` int(11) DEFAULT '0',
  `total_comments` int(11) DEFAULT '0',
  `total_likes` int(11) DEFAULT '0',
  `total_dislikes` int(11) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=latin1;

/* data for Table post */
INSERT INTO `post` VALUES (1,"Where does it come from ","                                                                                                                                                                                                    It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using Content here, content her, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for lorem ipsum will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).\r\n<br><br>\r\n<blockquote>\r\nThere are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable. \r\n</blockquote>\r\n<br><br>\r\n+ If you are going to use a passage of Lorem Ipsum,<br>\r\n+ You need to be sure there isnt anything embarrassing hidden in the middle of text.<br> \r\n+ All the Lorem Ipsum generators<br>\r\n<br><br>\r\nInternet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.                                                                                                                                                                        ","WhatsApp Image 2018-07-24 at 8.26.52 AM.jpeg","2018-07-28 21:57:27",18,3,5,0);
INSERT INTO `post` VALUES (2,"Where does it come from?","                                                                                                                It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using Content here, content her, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for lorem ipsum will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).\r\n<br><br>\r\n<blockquote>\r\nThere are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable. \r\n</blockquote>\r\n<br><br>\r\n+ If you are going to use a passage of Lorem Ipsum,<br>\r\n+ You need to be sure there isnt anything embarrassing hidden in the middle of text.<br> \r\n+ All the Lorem Ipsum generators<br>\r\n<br><br>\r\nInternet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.                                                                                                ","smiley-1282457__340.jpg","2018-07-28 21:57:27",31,4,5,5);
INSERT INTO `post` VALUES (5,"Where does it come from?","                                                                                                                It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using Content here, content her, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for lorem ipsum will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).\r\n<br><br>\r\n<blockquote>\r\nThere are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable. \r\n</blockquote>\r\n<br><br>\r\n+ If you are going to use a passage of Lorem Ipsum,<br>\r\n+ You need to be sure there isnt anything embarrassing hidden in the middle of text.<br> \r\n+ All the Lorem Ipsum generators<br>\r\n<br><br>\r\nInternet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.                                                                                                ","smiley-1282457__340.jpg","2018-07-28 21:57:27",24,4,5,5);
INSERT INTO `post` VALUES (6,"Where does it come from?","                                                                                                                It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using Content here, content her, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for lorem ipsum will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).\r\n<br><br>\r\n<blockquote>\r\nThere are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable. \r\n</blockquote>\r\n<br><br>\r\n+ If you are going to use a passage of Lorem Ipsum,<br>\r\n+ You need to be sure there isnt anything embarrassing hidden in the middle of text.<br> \r\n+ All the Lorem Ipsum generators<br>\r\n<br><br>\r\nInternet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.                                                                                                ","smiley-1282457__340.jpg","2018-07-28 21:57:27",23,4,5,5);
INSERT INTO `post` VALUES (7,"Where does it come from ","                                                                                                                                                                                                    It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using Content here, content her, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for lorem ipsum will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).\r\n<br><br>\r\n<blockquote>\r\nThere are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable. \r\n</blockquote>\r\n<br><br>\r\n+ If you are going to use a passage of Lorem Ipsum,<br>\r\n+ You need to be sure there isnt anything embarrassing hidden in the middle of text.<br> \r\n+ All the Lorem Ipsum generators<br>\r\n<br><br>\r\nInternet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.                                                                                                                                                                        ","WhatsApp Image 2018-07-24 at 8.26.52 AM.jpeg","2018-07-28 21:57:27",13,3,5,0);
INSERT INTO `post` VALUES (8,"Where does it come from ","                                                                                                                                                                                                    It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using Content here, content her, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for lorem ipsum will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).\r\n<br><br>\r\n<blockquote>\r\nThere are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable. \r\n</blockquote>\r\n<br><br>\r\n+ If you are going to use a passage of Lorem Ipsum,<br>\r\n+ You need to be sure there isnt anything embarrassing hidden in the middle of text.<br> \r\n+ All the Lorem Ipsum generators<br>\r\n<br><br>\r\nInternet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.                                                                                                                                                                        ","WhatsApp Image 2018-07-24 at 8.26.52 AM.jpeg","2018-07-28 21:57:27",13,3,5,0);

/* Table structure for user */
CREATE TABLE `user` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varbinary(256) DEFAULT NULL,
  `password` varchar(512) DEFAULT NULL,
  `name` varchar(256) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

/* data for Table user */
INSERT INTO `user` VALUES (1,"admin","$2y$10$mrwycAH4yA3tWSBLN92zvOKAw4JeaPSMdYxRJMUH8L3GVko/WUmzG","admin");

/* Restore session variables to original values */
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
